[project]
name = "assignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.0",
    "dotenv>=0.9.9",
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "django-stubs[compatible]>=5.2.5",
]
