# Generated by Django 5.0 on 2025-09-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="movies",
            new_name="Movie",
        ),
    ]
